int SET_initial_CONDITION_velocity_fixed_value(in I);
int SET_initial_CONDITION_velocity_mass_is_mooving(in I);
int SET_initial_CONDITION_phase_fraction_ascii_map(in I);
int SET_initial_CONDITION_pressure_fixed_value_with_hydrostatic_pressure(in I);
