#define AVALANCHE 1
#define TERMOGAS 0

typedef struct init_parameters_avalanche {
	char map_name[100];
	char region_map_name[100];
	double hight;
	int kx, ky, kz;
	int nx, ny, nz;
	int n_bl_x, n_bl_y, n_bl_z;
	int ncols;
	int nrows;
	double cellsize;
	double *mass;
	int *ind;
	int *bl_cond;
	int n_points, n_cells;
	int n_points_multipl;
	int n_cells_multipl;
	int *ind_multipl, *ind_cell_multipl;
	double interpolation, interpolation_poli;
	double *mass1;
	double nodata_value;
	int *snow_region;
	double depth;
	double density_snow, density_air;
	double pressure_atmosphere;
	double g[3];
	double k_viscosity_snow, k_viscosity_air;
	double *normal, *volume, *area;
	double dt, dx[3];
	double *B, *Aelem_csr, *B_prev;
	int *Ajptr_csr, *Aiptr_csr;
	int num_parameters;
	double shear_rate_0,limiting_viscosity_snow, flow_index, yield_stress;
	int system_dimension, system_dimension_with_boundary;
	int non_zero_elem;
	int A_ind_current;
	int flag_first_time_step;
	double end_time;
	int stencil_size;
	int *ind_boundary_cells, n_boundary_cells;
	double mass_quantity;
} in_avalanche;

typedef struct init_parameters_termogas {
	char map_name[100];
	char region_map_name[100];
	double hight;
	int kx, ky, kz;
	int nx, ny, nz;
	int n_bl_x, n_bl_y, n_bl_z;
	int ncols;
	int nrows;
	double cellsize;
	double *mass;
	int *ind;
	int *bl_cond;
	int n_points, n_cells;
	int n_points_multipl;
	int n_cells_multipl;
	int *ind_multipl, *ind_cell_multipl;
	double interpolation, interpolation_poli;
	double *mass1;
	double nodata_value;
	double *normal, *volume, *area;
	double dt, dx[3];
	double *B, *Aelem_csr, *B_prev;
	int *Ajptr_csr, *Aiptr_csr;
	int num_parameters;
	int system_dimension, system_dimension_with_boundary;
	int non_zero_elem;
	int A_ind_current;
	int flag_first_time_step;
	double end_time;
	int stencil_size;
	int *ind_boundary_cells, n_boundary_cells;
	double mass_quantity;
	double porousness;
	double density_0[2];
	double pressure_0;
	double density_coef_beta[2];
	double temperature_0;
	double density_coef_a[2];
	double R;
	double molar_weight[4];
	double permeability;
	double relative_saturation[3];
	double viscosity_coef_A[2];
	double viscosity_coef_A_gas[4];
	double viscosity_coef_B[2];
	double viscosity_coef_C_gas[4];
	double capillary_pressure_at_maximum_saturation[3];
	double residual_saturation[3];
	double capillary_pressure_coef;
} in_termogas;

typedef in_avalanche in;

int set_parameters_avalanche(in *I);
int set_parameters_termogas(in *I);
