typedef struct init_parameters {
	char *map_name;
	char *region_map_name;
	double hight;
	int kx, ky, kz;
	int nx, ny, nz;
	int n_bl_x, n_bl_y, n_bl_z;
	int ncols;
	int nrows;
	double cellsize;
	double *mass;
	int *ind;
	int *bl_cond;
	int n_points, n_cells;
	int n_points_multipl, n_cells_multipl;
	int *ind_multipl, *ind_cell_multipl;
	double interpolation, interpolation_poli;
	double *mass1;
	double nodata_value;
	int *snow_region;
	double depth;
	double density_snow, density_air;
	double pressure_atmosphere;
	double g[3];
	double k_viscosity_snow, k_viscosity_air;
	double *normal, *volume, *area;
	double dt, dx[3];
	double *B, *Aelem_csr, *B_prev;
	int *Ajptr_csr, *Aiptr_csr;
	int num_parameters;
	double shear_rate_0,limiting_viscosity_snow, flow_index, yield_stress;
	int system_dimension, system_dimension_with_boundary;
	int non_zero_elem;
	int A_ind_current;
	int flag_first_time_step;
	double end_time;
	int stencil_size;
	int *ind_boundary_cells, n_boundary_cells;
	double mass_quantity;
} in;

int set_parameters(in I);
