double density(int i, int j, int k);
double velocity(int p, int i, int j, int k);
double phase_fraction(int i, int j, int k);
double pressure(int i, int j, int k);
double velocity_on_face(int p, int i, int j, int k, int s);
double density_on_face(int i, int j, int k, int s);
double strain_rate_on_face(int i, int j, int k, int s, int m, int n);
double shear_rate_on_face(int i, int j, int k, int s);
double phase_fraction_on_face(int i, int j, int k, int s);
double effective_viscosity_on_face(int i, int j, int k, int s);
double pressure_on_face(int i, int j, int k, int s);
int A_IND_S(int p, int i, int j, int k, int s);
int A_IND_S_SWITCH(int i, int j, int k, int s);
int A_IND(int p, int i, int j, int k);
int B_IND(int p, int i, int j, int k);
int AREA_IND(int i, int j, int k, int s);
int NORMAL_IND(int p, int i, int j, int k, int s);
int VOLUME_IND(int i, int j, int k);
int check_for_corrupt_cell(int i, int j, int k);
int write_to_A_csr(int p_eq, int i_eq, int j_eq, int k_eq, int p, int i, int j, int k, int s, double value);
